---
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-symlinks
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
    -   id: forbid-new-submodules

-   repo: git://github.com/guykisel/prospector-mirror
    sha: 'b27f281eb9398fc8504415d7fbdabf119ea8c5e1'
    hooks:
    -   id: prospector

-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: forbid-crlf
    -   id: forbid-tabs

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-lll]
        files: .py$

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
