---
strictness: high
doc-warnings: true
test-warnings: true

pep8:
  options:
    max-line-length: 99
  disable:
    - E722

pylint:
  options:
    max-args: 6
    max-line-length: 99
  disable:
    - C0111
    - C0103
    - F0401
    - R0913
    - R0914
    - W0703

pep257:
  disable:
    - D100
    - D104
    - D203
    - D213
    - D406
    - D407

mccabe:
  run: false
